#!/bin/sh
# Downloads the web fonts used by the site and generates fonts/fonts.css.
#
# The site must not load fonts from fonts.googleapis.com at run time: doing so
# sends every visitor's IP address to Google without consent. Instead the font
# files are fetched once, committed to the repo and served from our own domain.
# Re-run this script only when the set of families or weights changes.
#
# Space Grotesk, Inter and Space Mono are all SIL Open Font License, so
# redistributing the files from our own server is permitted.
#
# Usage:  sh fonts/fetch-fonts.sh

# Stop immediately if any command fails.
set -e

# Resolve the directory this script lives in, so it works from any cwd.
DIR=$(cd "$(dirname "$0")" && pwd)

# Families and weights, matching the --display/--body/--mono vars in style.css.
FAMILIES="family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600&family=Space+Mono:wght@400;700"

# Latin plus latin-ext; the latter carries the Hungarian ő and ű.
SUBSETS="subset=latin,latin-ext"

# Google only serves woff2 to browsers it recognises, hence the browser UA.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Fetch the stylesheet that lists the actual font file URLs.
echo "Fetching stylesheet..."
curl -fsS -A "$UA" "https://fonts.googleapis.com/css2?${FAMILIES}&display=swap&${SUBSETS}" -o "$DIR/google.css"

# Extract one "remote-url<TAB>local-filename" pair per @font-face block.
# Google precedes each block with a comment naming the subset, e.g. /* latin-ext */.
awk '
  /^\/\*/                 { subset = $2; next }
  /font-family:/          { f = $0; sub(/.*font-family: *.?/, "", f); sub(/.;.*/, "", f);
                            gsub(/ /, "-", f); family = tolower(f) }
  /font-weight:/          { weight = $2; sub(/;/, "", weight) }
  /src: *url\(/           { u = $0; sub(/.*url\(/, "", u); sub(/\).*/, "", u);
                            print u "\t" family "-" weight "-" subset ".woff2" }
' "$DIR/google.css" > "$DIR/manifest.txt"

# Start the generated stylesheet from the upstream one, then rewrite each URL.
cp "$DIR/google.css" "$DIR/fonts.css"

# Download every font file and point the generated CSS at the local copy.
while IFS='	' read -r url name; do
    # Skip blank lines defensively.
    [ -n "$url" ] || continue
    echo "  $name"
    curl -fsS -A "$UA" "$url" -o "$DIR/$name"
    # Replace the absolute Google URL with a site-relative path. The URLs
    # contain slashes, so use | as the sed delimiter.
    sed -i.bak "s|$url|/fonts/$name|" "$DIR/fonts.css"
    rm -f "$DIR/fonts.css.bak"
done < "$DIR/manifest.txt"

# Prepend a note so nobody hand-edits the generated file.
printf '/* Generated by fonts/fetch-fonts.sh. Do not edit by hand. */\n' > "$DIR/fonts.css.new"
cat "$DIR/fonts.css" >> "$DIR/fonts.css.new"
mv "$DIR/fonts.css.new" "$DIR/fonts.css"

# Remove the intermediates; only fonts.css and the .woff2 files are committed.
rm -f "$DIR/google.css" "$DIR/manifest.txt"

# Report what landed on disk.
echo "Done. $(ls "$DIR" | grep -c '\.woff2$') font files written to fonts/"
